/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import Proyecto.Grafo;
import javax.swing.JOptionPane;

/**
 *Clase CoberturaTotal  como parte de la ui.
 */
public class CoberturaTotal extends javax.swing.JFrame {

    /**
     * Creates new form VisualizarCobertura
     */
    static Grafo grafo;
    
    /**
     * 
     * @param grafo 
     */
    public CoberturaTotal(Grafo grafo) {
        initComponents();
        this.grafo = grafo;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ConsultarBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cobertura Total");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 200, 40));

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setText("Atrás");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 80, 40));

        ConsultarBTN.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ConsultarBTN.setText("Consultar");
        ConsultarBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ConsultarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 110, 40));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 330, 220));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Paradas no cubiertas por alguna sucursal:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fondo.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ConsultarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarBTNActionPerformed
        
        this.profundidadCoberturaTotal(grafo);
        
    }//GEN-LAST:event_ConsultarBTNActionPerformed
    
    /**
     * Método para recorrer la profundidad con la cobertura total.
     * @param g
     * @param v
     * @param cubiertos
     * @param t 
     */
    public void recorrerProfundidadCoberturaTotal (Grafo g, int v, boolean [ ] cubiertos, int t) {
        try{
            if (t>0){
                //se marca el vértice v como visitado
                
                cubiertos [v] = true    ;
                //se examinan los vértices adyacentes a v para continuar el recorrido
                for (int i = 0; i < g.getnVert(); i++) {                    
                    if ((v != i) && (!cubiertos [i]) && (g.existeArco(v, i)) )
                        recorrerProfundidadCoberturaTotal (g, i, cubiertos, t-1);
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error, recorrido por profundidad fallido" + e.getMessage()); 
        }
        
    }

    /**
     * 
     * @param g 
     */
    public void profundidadCoberturaTotal (Grafo g) {
        try
        {
            int t = g.getT();
            boolean existeSucursal = true;
            boolean cubiertos [ ] = new boolean [g.getnVert()];

            for (int i = 0; i < g.getnVert(); i++) //inicializar vector con campos false
                cubiertos [i] = false;
        
            for (int n = 0; n < g.getnVert(); n++){ //Relanza el recorrido en cada
                if (g.getVerticeI(n).isSucursal()){
                    //if (!cubiertos [n]) //vértice visitado
                        recorrerProfundidadCoberturaTotal (g, n, cubiertos, t+1);
                }
            }
            
            for(int i= 0;i<cubiertos.length;i++){
                if(!cubiertos[i])
                    this.imprimirParadas(g, i);
                else
                    existeSucursal = false;
                
            }
            
            if (!existeSucursal)
                JOptionPane.showMessageDialog(this, "Todas las paradas están cubiertas");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error en la consulta" + e.getMessage());
        }
    }
    
    /**
     * Método para imprimir las paradas
     * @param g
     * @param v 
     */
    public void imprimirParadas(Grafo g, int v){
        try{
            String nombreVertice = "";
            if (g.getVerticeI(v).getCompuesto().equals(""))
                nombreVertice = g.getVerticeI(v).getNombre();
            else
                nombreVertice = g.getVerticeI(v).getNombre() + "/" + g.getVerticeI(v).getCompuesto() ;
            //System.out.println ("Paradas: " + v + ": " + nombreVertice);
            this.jTextArea1.setText(this.jTextArea1.getText() + "Parada: " + nombreVertice + "\n");
            
            System.out.println ("Parada: " + v + ": " + nombreVertice);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error, impresión fallida" + e.getMessage()); 
        }
    }
    
//    public void sugerirSucursales(){
//        
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoberturaTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoberturaTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoberturaTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoberturaTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoberturaTotal(grafo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultarBTN;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
