/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import Proyecto.Cola;
import Proyecto.Grafo;
import Proyecto.Nodo;
import javax.swing.JOptionPane;

/**
 *Clase CoberturaSucursales como parte de la UI.
 */
public class CoberturaSucursales extends javax.swing.JFrame {

    /**
     * Creates new form VisualizarCobertura
     */
    
    static Grafo grafo;
    
    /**
     * Iniciio de los componentes
     * @param grafo 
     */
    public CoberturaSucursales(Grafo grafo) {
        initComponents();
        //this.ComboBox.removeAllItems();
        this.grafo = grafo;
        this.recorrerSucursales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        AmplitudBtn = new javax.swing.JButton();
        ComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Búsqueda por Amplitud");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        AmplitudBtn.setText("Amplitud");
        AmplitudBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmplitudBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AmplitudBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 100, -1));

        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 190, 30));

        jLabel2.setText("Selecciona una sucursal:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 160, -1));

        jButton3.setText("Profundidad");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 100, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 120));

        jLabel3.setText("Alcance de la sucursal:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * no se no deja borrarlo
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * Método para recorrer las sucursales.
     */
    public void recorrerSucursales(){
        this.ComboBox.removeAllItems();
        for(int i = 0; i<this.grafo.getTablAd().length;i++){
            if (CoberturaSucursales.grafo.getTablAd()[i].isSucursal()){
                String nombrevertice = CoberturaSucursales.grafo.getTablAd()[i].getNombre();
                this.ComboBox.addItem(nombrevertice);
            }
        }
    }
    
    /**
     * Método para hallar la amplitud 
     * @param g
     * @param numVertice 
     */
    public void amplitud (Grafo g, int numVertice) {
        try{
            int t = 1;
            Cola cola = new Cola ();
            Nodo aux;
            boolean visitados [ ] = new boolean [g.getnVert()];
            int v = 0; //vértice actual
            //Se inicializa el vector visitados [] a false
            for (int i = 0; i < g.getnVert(); i++)
                visitados [i] = false;

            //El recorrido en amplitud se inicia en cada vértice no visitado
            //for (int n = 0; n < g.getnVert(); n++) {
                    //se pone en la cola el vértide de partida y se marca como visitado
                    //if (!visitados [numVertice]){
                            cola.encolar (numVertice);
                            visitados [numVertice] = true;
                            this.imprimirParadas(g, numVertice);
                            while (!cola.EsVacio() && (t>0)) {
                                    aux = cola.desencolar();
                                    v = (int)aux.getValor();//desencolar y tratar el vértice
                                    //System.out.println (v);
                                    //y encolo los nodos adyacentes a v.
                                    for (int j = 0; j < g.getnVert(); j++){
                                            if ((v !=j) && (g.existeArco(v, j) && (!visitados [j]))) {
                                                    cola.encolar ( j );
                                                    visitados [j] = true;
                                                    this.imprimirParadas(g, j);
                                            }
                                    }
                                    t--;
                            }
                    //}
            //}
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error, recorrido por amplitud fallido" + e.getMessage()); 
        }
	
	
    }
    
    /**
     * Método para recorrido en profundidad
     * @param g Objeto grafo
     * @param v Indice del vertice
     * @param visitados lista que contiene cuales vertices han sido o no visitados
     * @param t Frecuencia de las sucursales del grafo
     */
    public void recorrerProfundidad (Grafo g, int v, boolean [ ] visitados, int t) {
        try{
            if (t>0){
                //se marca el vértice v como visitado
                visitados [v] = true;
                this.imprimirParadas(g, v);
                //el tratamiento del vértice consiste únicamente en imprimirlo en pantalla
                
                //se examinan los vértices adyacentes a v para continuar el recorrido
                for (int i = 0; i < g.getnVert(); i++) {
                        if ((v != i) && (!visitados [i]) && (g.existeArco(v, i)) )
                                recorrerProfundidad (g, i, visitados, t-1);
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error, recorrido por profundidad fallido" + e.getMessage()); 
        }
    }

    /**
     * Método recorrido en profundidad parte 1
     * @param g Objeto grafo
     */
    public void profundidad (Grafo g) {
        String nombreVertice = this.ComboBox.getSelectedItem().toString();
        int indiceVertice = g.getNumVertice(nombreVertice);
        int t = g.getT();
	boolean visitados [ ] = new boolean [g.getnVert()];
	for (int i = 0; i < g.getnVert(); i++) //inicializar vector con campos false
            visitados [i] = false;
        
        //for (int n = indiceVertice; n < 2; n++){ //Relanza el recorrido en cada
        //if (!visitados [indiceVertice]) //vértice visitado
        recorrerProfundidad (g, indiceVertice, visitados, t+1);
        //}
        
    }
    
    /**
     * Función que le envía al TextArea la información del vértice.
     * @param g El objeto grafo 
     * @param v Indice del vertice a imprimir
     */
    public void imprimirParadas(Grafo g, int v){
        try{
            String nombreVertice = "";
            if (g.getVerticeI(v).getCompuesto().equals(""))
                nombreVertice = g.getVerticeI(v).getNombre();
            else
                nombreVertice = g.getVerticeI(v).getNombre() + "/" + g.getVerticeI(v).getCompuesto() ;
            //el tratamiento del vértice consiste únicamente en imprimirlo en pantalla
            this.jTextArea1.setText(this.jTextArea1.getText() + "Parada: " + nombreVertice + "\n");
            
            System.out.println ("Parada: " + v + ": " + nombreVertice);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error, impresión fallida" + e.getMessage()); 
        }
    }
    
    /**
     * Botón que llama a la función amplitud.
     * @param evt 
     */
    private void AmplitudBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmplitudBtnActionPerformed
        String nombreVertice = this.ComboBox.getSelectedItem().toString();
        int indiceVertice = grafo.getNumVertice(nombreVertice);
        this.jTextArea1.setText("");
        this.amplitud(this.grafo, indiceVertice);
    
    }//GEN-LAST:event_AmplitudBtnActionPerformed
    /**
     * 
     * @param evt 
     */
    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxActionPerformed
    
    /**
     * 
     * @param evt 
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.jTextArea1.setText("");
        this.profundidad(this.grafo);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoberturaSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoberturaSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoberturaSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoberturaSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoberturaSucursales(grafo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AmplitudBtn;
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
