/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;


import Proyecto.*;
import Reader.Reader;
import static UI.CargaRed_1.grafo;
import java.math.MathContext;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.view.Viewer;

/**
 *
 * @author HP
 */
public class MenuSucursales extends javax.swing.JFrame {

    /**
     * Creates new form MenuSucursales
     */
    
    static Grafo grafo ;
    
    

    public MenuSucursales(Grafo grafo) {
        this.grafo = grafo;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cargar_Redes = new javax.swing.JButton();
        Mostrar_Grafo = new javax.swing.JButton();
        Establecer_t = new javax.swing.JButton();
        Colocar_Sucursal = new javax.swing.JButton();
        Ver_Cobertura = new javax.swing.JButton();
        Agregar_Linea = new javax.swing.JButton();
        Cargar_Red = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        establecerTxt = new javax.swing.JTextField();
        establecerBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        Cargar_Redes.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        Cargar_Redes.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Cargar_Redes.setForeground(new java.awt.Color(255, 255, 255));
        Cargar_Redes.setText("Cargar Redes");
        Cargar_Redes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mostrar_Grafo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Mostrar_Grafo.setText("Mostrar Grafo");
        Mostrar_Grafo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Mostrar_Grafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_GrafoActionPerformed(evt);
            }
        });
        getContentPane().add(Mostrar_Grafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 170, 40));

        Establecer_t.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Establecer_t.setText("Establecer t");
        Establecer_t.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Establecer_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Establecer_tActionPerformed(evt);
            }
        });
        getContentPane().add(Establecer_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 170, 40));

        Colocar_Sucursal.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Colocar_Sucursal.setText("Colocar Sucursal");
        Colocar_Sucursal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Colocar_Sucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Colocar_SucursalActionPerformed(evt);
            }
        });
        getContentPane().add(Colocar_Sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 170, 40));

        Ver_Cobertura.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Ver_Cobertura.setText("Ver  Cobertura");
        Ver_Cobertura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Ver_Cobertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_CoberturaActionPerformed(evt);
            }
        });
        getContentPane().add(Ver_Cobertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 170, 40));

        Agregar_Linea.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Agregar_Linea.setText("Agregar Línea");
        Agregar_Linea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Agregar_Linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 170, 40));

        Cargar_Red.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Cargar_Red.setText("Cargar nueva Red");
        Cargar_Red.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cargar_Red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cargar_RedActionPerformed(evt);
            }
        });
        getContentPane().add(Cargar_Red, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 170, 40));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Establezca la frecuencia de sus sucursales ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));
        getContentPane().add(establecerTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 130, -1));

        establecerBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        establecerBtn.setText("Establecer");
        establecerBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        establecerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                establecerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(establecerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 90, 30));

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fondo-logo.png"))); // NOI18N
        jLabel3.setText("Establezca la frecuencia de sus sucursales:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    private void Mostrar_GrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_GrafoActionPerformed
    MostrarGrafo mg = new MostrarGrafo();
    System.out.println(grafo.toString());
        try {
            Graph graph = mg.mostrar(grafo);
            graph.display();
                    
        } catch (Exception ex) {
            Logger.getLogger(MenuSucursales.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_Mostrar_GrafoActionPerformed

    private void Ver_CoberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_CoberturaActionPerformed
        MenuCobertura pantalla = new MenuCobertura(this.grafo);
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_Ver_CoberturaActionPerformed

    private void establecerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_establecerBtnActionPerformed
        int frecuencia = 1;
        try{
            frecuencia = Integer.parseInt(this.establecerTxt.getText());
            this.grafo.setT(frecuencia);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error, Dato inválido" + e.getMessage());
        }
    }//GEN-LAST:event_establecerBtnActionPerformed

    private void Establecer_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Establecer_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Establecer_tActionPerformed

    private void Colocar_SucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Colocar_SucursalActionPerformed
        MostrarGrafo mg = new MostrarGrafo();
        ColocarSucursal pantalla= new ColocarSucursal(MenuSucursales.grafo,mg);
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
        
    }//GEN-LAST:event_Colocar_SucursalActionPerformed

    private void Cargar_RedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cargar_RedActionPerformed
          try{
          Grafo grafo_nuevo = new Grafo(0, "");
          Reader reader = new Reader();
          grafo_nuevo = reader.Read();
          
          if(grafo_nuevo ==  null){
              throw new Exception("Error durante la carga");  
          }
          grafo = grafo_nuevo;
          
          JOptionPane.showMessageDialog(this, "La carga fue un exito");  

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error durante la carga");  
        }
   
        
    }//GEN-LAST:event_Cargar_RedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuSucursales(grafo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_Linea;
    private javax.swing.JButton Cargar_Red;
    private javax.swing.JButton Cargar_Redes;
    private javax.swing.JButton Colocar_Sucursal;
    private javax.swing.JButton Establecer_t;
    private javax.swing.JButton Mostrar_Grafo;
    private javax.swing.JButton Ver_Cobertura;
    private javax.swing.JButton establecerBtn;
    private javax.swing.JTextField establecerTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
